### PR TITLE
fix: module checkout page import documentation example

### PR DESCRIPTION
**Pull request by bokjo**
Fixed typo in docs.

## Description

Fixed import path in docs.

## Related Issue

https://github.com/Baroshem/nuxt-adyen-module/issues/23

## Motivation and Context

Wrong examples in the documentation lead to confusion.

## How Has This Been Tested?

N/A

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by bokjo** [comment]
```sh
i.e. <http://localhost:8080/checkout> should be something like https://checkout-test.adyen.com (depending on your env. [test or live]
```

`checkoutEndpoint` is not really needed actually, it is derived from the `environment: TEST | LIVE` value and will be set by the ayden-lib with peoper URL for their API.

I'll leave it up to you to decide whether to put `https://checkout-test.adyen.com` as value in the documentation or something else... `http://localhost:8080/checkout` is definitely wrong and misleading however.

**Comment by bokjo** [comment]
p.s I'm not Frontend dev. and don't know how Vue, Nuxt work in detail.. but can you export the `AdyenCheckout.vue` component I suppose as normal JS export 

So this
```js
import AdyenCheckout from 'nuxt-adyen-module/dist/runtime/AdyenCheckout.vue';
```

Will become something like, for example
```js
import { AdyenCheckoutPage } from 'nuxt-adyen-module';
```

**Comment by Baroshem** [comment]
Hi @bokjo

Thank you for this PR. Verall it looks good. I will take a look at it later this week as I am currently abroad. But definitely this should be added 😉

**Comment by Baroshem** [comment]
Hi @bokjo 

I had a chance to look at your PR. The proposition to change the path to the AdyenCheckout component is right. It should be something like this:

```ts
import AdyenCheckout from 'nuxt-adyen-module/dist/runtime/AdyenCheckout.vue'
```

Could you also modify the path in the README.md file so that the import path in every place will be updated accordingly? :)

Importing directly from package wont work as you expect. Vue components are exported in a default way so they cannot be destructured like this:

```
import { AdyenCheckoutPage } from 'nuxt-adyen-module';
```

**Comment by bokjo** [comment]
@Baroshem @here done!

**Pull request merged**
